default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dictionary_api_development

test:
  <<: *default
  database: dictionary_api_test

production:
  <<: *default
  database: dictionary_api_production
  username: dictionary_api
  password: <%= ENV['DICTIONARY_API_DATABASE_PASSWORD'] %>
